Create adventOfCode062022.hs
github/codespaces-blank pull request #3
Opened 2022-12-21 16:15 UTC by Anonymus-2022

"main" was an help of my University. I didn't pay attention to the runtime.
I'm a student and I'm happy about any improvements to the code

2023-01-11 14:15 UTC, janiaz708 commented
hi

2023-01-12 17:30 UTC, Resultsvary777 commented
Hi

On Wed, Jan 11, 2023, 8:15 AM janiaz708 ***@***.***> wrote:

> hi
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/github/codespaces-blank/pull/3#issuecomment-1378818339>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2XVMEUKHLMWDLO4FTMQ23LWR26BVANCNFSM6AAAAAATFZM3NM>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-01-12 19:33 UTC, janiaz708 commented on adventOfCode062022.hs
> +
dostuff   content

2023-01-14 00:13 UTC, liedlgruber commented
Anonymus-2022:patch-1

2023-01-14 00:14 UTC, liedlgruber approved these changes

2023-01-14 00:14 UTC, liedlgruber reviewed
adventOfCode062022.hs

2023-01-14 00:15 UTC, liedlgruber commented
https://github.com/github/codespaces-blank/pull/3#pullrequestreview-1248676351

2023-01-14 00:16 UTC, liedlgruber requested changes
vierGleiche (a:b:c:d:ds) = if ((length (a:b:c:d:ds))<4)
    then[False]
    else if ((a==b) || (a==c) || (a==d) || (b==c) || (b==d) || (c==d))
        then False : (vierGleiche (b:c:d:ds))
        else [True]


--the length of the datastream until the start-of-packet

2023-01-14 00:19 UTC, liedlgruber approved these changes

2023-01-14 00:19 UTC, liedlgruber commented on adventOfCode062022.hs
> +
adventOfCode062022.hs

2023-01-14 00:19 UTC, liedlgruber commented on adventOfCode062022.hs
> +    putStrLn ""
doStuff :: String -> IO ()
doStuff content = do
    putStrLn (solution6 content)putStrLn (solution62 content)
    putStrLn ""

2023-01-14 00:21 UTC, liedlgruber approved these changes
adventOfCode062022.hs

2023-01-14 00:21 UTC, liedlgruber requested changes
adventOfCode062022.hs

2023-02-25 06:44 UTC, Diamondbrandblue commented
Im happy to work with it

2023-02-25 06:45 UTC, Diamondbrandblue approved these changes
Im working on figuring out differential nonsplit

2023-05-07 20:47 UTC, Domi88sss approved these changes

2023-05-07 20:47 UTC, Domi88sss approved these changes

2023-05-07 20:47 UTC, Domi88sss approved these changes

2023-06-02 08:34 UTC, macrombilux commented
> hi

2023-06-02 08:35 UTC, macrombilux commented on adventOfCode062022.hs
> +
🚀

2023-08-11 21:17 UTC, Charisma-Mua commented on adventOfCode062022.hs
> +
That is cool. Please can I get a project?

2024-05-11 11:48 UTC, Dioliode approved these changes
DioX

2024-11-19 10:16 UTC, closed without merging